sonar.projectKey=joshiel123_UCV-SI-lab11
sonar.organization=joshiel123
sonar.projectName=UCV Alpha Beta Lab

# Mapeo de directorios exigido por el profesor
sonar.sources=src
sonar.tests=tests

# Telemetría de Cobertura obligatoria para SonarCloud
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
