# Credenciales de tu proyecto en SonarCloud
sonar.projectKey=joshiel123_UCV-SI-lab11
sonar.organization=joshiel123
sonar.projectName=UCV-SI-lab11

# Rutas exigidas por el laboratorio para el análisis
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
