sonar.projectKey=joshiel123_UCV-SI-lab11
sonar.organization=joshiel123

# Rutas de análisis
sonar.sources=src
sonar.tests=tests

# Telemetría de Cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
